/cluster/home/oilter/begin.sh: line 1: env2lmod: command not found
Namespace(cfg='/cluster/home/oilter/PIDNet/configs/p4b/pidnet_small_p4b_storage.yaml', opts=[], seed=304)
AUTO_RESUME: False
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  DATASET: p4b
  EXTRA_TRAIN_SET: 
  NUM_CLASSES: 19
  ROOT: /cluster/scratch/oilter/data/
  TEST_SET: list/p4b/train.lst
  TRAIN_SET: list/p4b/train.lst
GPUS: (0, 1)
LOG_DIR: log
LOSS:
  BALANCE_WEIGHTS: [0.4, 1.0]
  CLASS_BALANCE: False
  OHEMKEEP: 131072
  OHEMTHRES: 0.9
  SB_WEIGHTS: 1.0
  USE_OHEM: True
MODEL:
  ALIGN_CORNERS: True
  NAME: pidnet_small
  NUM_OUTPUTS: 2
  PRETRAINED: /cluster/home/oilter/PIDNet/pretrained_models/cityscapes/PIDNet_S_Cityscapes_test.pt
OUTPUT_DIR: /cluster/scratch/oilter/output
PIN_MEMORY: True
PRINT_FREQ: 10
TEST:
  BASE_SIZE: 1920
  BATCH_SIZE_PER_GPU: 1
  FLIP_TEST: False
  IMAGE_SIZE: [1920, 1080]
  MODEL_FILE: 
  MULTI_SCALE: False
  OUTPUT_INDEX: 1
TRAIN:
  BASE_SIZE: 1920
  BATCH_SIZE_PER_GPU: 2
  BEGIN_EPOCH: 0
  END_EPOCH: 484
  EXTRA_EPOCH: 0
  EXTRA_LR: 0.001
  FLIP: True
  IGNORE_LABEL: 255
  IMAGE_SIZE: [1920, 1080]
  LR: 0.01
  MOMENTUM: 0.9
  MULTI_SCALE: True
  NESTEROV: False
  OPTIMIZER: sgd
  RESUME: False
  SCALE_FACTOR: 16
  SHUFFLE: True
  WD: 0.0005
WORKERS: 6
Attention!!!
Loaded 479 parameters!
Over!!!
Seeding with 304
=> creating /cluster/scratch/oilter/output/p4b/pidnet_small_p4b_storage
=> creating log/p4b/pidnet_small/pidnet_small_p4b_storage_2023-02-18-16-00
/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/nn/functional.py:1960: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
Epoch: [0/484] Iter:[0/100], Time: 7.16, lr: [0.01], Loss: 7.699513, Acc:0.472411, Semantic loss: 2.893409, BCE loss: 2.885995, SB loss: 1.920109
Epoch: [0/484] Iter:[10/100], Time: 1.07, lr: [0.00999814047665656], Loss: 6.684299, Acc:0.425276, Semantic loss: 2.087530, BCE loss: 2.966443, SB loss: 1.630326
Traceback (most recent call last):
  File "/cluster/home/oilter/PIDNet/tools/train.py", line 218, in <module>
    main()
  File "/cluster/home/oilter/PIDNet/tools/train.py", line 182, in main
    trainloader, optimizer, model, writer_dict)
  File "/cluster/home/oilter/PIDNet/tools/../utils/function.py", line 43, in train
    losses, _, acc, loss_list = model(images, labels, bd_gts)
  File "/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
IndexError: Caught IndexError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/cluster/home/oilter/PIDNet/tools/../utils/utils.py", line 54, in forward
    loss_sb = self.sem_loss(outputs[-2], bd_label)
  File "/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/cluster/home/oilter/PIDNet/tools/../utils/criterion.py", line 97, in forward
    return sb_weights * self._ohem_forward(score[0], target)
  File "/cluster/home/oilter/PIDNet/tools/../utils/criterion.py", line 74, in _ohem_forward
    min_value = pred[min(self.min_kept, pred.numel() - 1)]
IndexError: index -1 is out of bounds for dimension 0 with size 0

